apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: finitech-api
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/finitech/api
    newTag: latest
