apiVersion: v1
kind: Service
metadata:
  name: finitech-api
  labels:
    app: finitech-api
spec:
  type: ClusterIP
  selector:
    app: finitech-api
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 81
      targetPort: 8081
      name: grpc
